[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && chmod +x start.sh && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "backend"
source = "backend"